package auth

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"testing"
)

// --- Cross-language golden vector --------------------------------------
//
// These fixed values were generated by the Erlang counterpart module
// asobi_saas_cli_crypto against the same HKDF info string, AES-256-GCM
// primitives, and P-256 curve. If either side drifts — wrong curve,
// wrong HKDF info, wrong key length — this test fails. Do not update
// these values unless the protocol is intentionally being versioned.
//
// Generation command (Erlang shell inside ~/ai/work/asobi_saas with
// the module loaded, using the same fixed private keys below):
//
//   ClientPriv = binary:decode_hex(<<"a1b2...eeff">>)
//   ServerPriv = binary:decode_hex(<<"1122...eeff">>)
//   {ClientPub, _} = crypto:generate_key(ecdh, secp256r1, ClientPriv)
//   {ServerPub, _} = crypto:generate_key(ecdh, secp256r1, ServerPriv)
//   Key = asobi_saas_cli_crypto:derive_shared_secret(ClientPub, ServerPriv)
//   {CT, Tag} = crypto:crypto_one_time_aead(
//       aes_256_gcm, Key, Nonce, Plaintext, <<>>, 16, true)

const (
	vectorClientPrivHex = "a1b2c3d4e5f60718293a4b5c6d7e8f9001112233445566778899aabbccddeeff"
	vectorClientPubHex  = "04fd2f012b4acaacb7aab51fadf6d54373122c7703eb5c1c792a2fd5aeced9f234f6063fa4a216643555fe8ca82da70be2c664ca7d57384bc9ba8558c9d6e67bbf"
	vectorServerPrivHex = "112233445566778899aabbccddeeff0011223344556677889900aabbccddeeff"
	vectorServerPubHex  = "04b73bc280d859eaaeba82af7db7f0ee1b64bec78d90b0a32fbdf86ec0b8e58f9a422beeda32a23e34f31ccb04e796a3cdac3919af3f2b9498f9781f58c97b4ca0"
	vectorDerivedKeyHex = "8c46085dd64b21789e560a1e96d73e559d4d3d15465f1a43e4528db532cc3411"
	vectorPlaintext     = "ak_fixed0_vector_encryption_test_payload_abc123"
	vectorNonceHex      = "0102030405060708090a0b0c"
	vectorCiphertextHex = "e4ead58c5005bd7618f56e4d12d1b8457bef7008d56de136cb7db4028d2edeeb1ecb110164ce77f4ad3219eac94d89"
	vectorTagHex        = "5a48f28cf5e622cf8f51a472cd7c695c"
)

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex fixture: %v", err)
	}
	return b
}

// TestGoldenVectorSharedSecret verifies that Go's ECDH + HKDF matches
// the pre-generated Erlang output exactly. If this fails we have a
// cross-language encoding bug somewhere (curve parameter shape, HKDF
// info string, salt handling).
func TestGoldenVectorSharedSecret(t *testing.T) {
	clientPub := mustHex(t, vectorClientPubHex)
	serverPriv := mustHex(t, vectorServerPrivHex)
	want := mustHex(t, vectorDerivedKeyHex)

	got, err := DeriveSharedSecret(clientPub, serverPriv)
	if err != nil {
		t.Fatalf("DeriveSharedSecret: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("derived key mismatch\n want: %x\n got:  %x", want, got)
	}

	// Both directions must derive the same key.
	serverPub := mustHex(t, vectorServerPubHex)
	clientPriv := mustHex(t, vectorClientPrivHex)
	got2, err := DeriveSharedSecret(serverPub, clientPriv)
	if err != nil {
		t.Fatalf("DeriveSharedSecret (reverse): %v", err)
	}
	if !bytes.Equal(got2, want) {
		t.Fatalf("derived key commutativity failed\n want: %x\n got:  %x", want, got2)
	}
}

// TestGoldenVectorDecrypt proves that Go can decrypt a ciphertext
// produced by the Erlang side. This is the round-trip interop check:
// the wire format for (nonce, ciphertext, tag) must be byte-identical
// across languages.
func TestGoldenVectorDecrypt(t *testing.T) {
	key := mustHex(t, vectorDerivedKeyHex)
	nonce := mustHex(t, vectorNonceHex)
	ciphertext := mustHex(t, vectorCiphertextHex)
	tag := mustHex(t, vectorTagHex)

	got, err := Decrypt(ciphertext, tag, nonce, key)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if string(got) != vectorPlaintext {
		t.Fatalf("plaintext mismatch\n want: %q\n got:  %q", vectorPlaintext, got)
	}
}

// --- Go-native round-trip ------------------------------------------------

func TestGenerateKeypairShape(t *testing.T) {
	kp, err := GenerateKeypair()
	if err != nil {
		t.Fatalf("GenerateKeypair: %v", err)
	}
	if len(kp.Public) != 65 {
		t.Errorf("public key should be 65 bytes (uncompressed P-256), got %d", len(kp.Public))
	}
	if len(kp.Private) != 32 {
		t.Errorf("private key should be 32 bytes, got %d", len(kp.Private))
	}
}

func TestRoundtripDecryptsCleanly(t *testing.T) {
	client, err := GenerateKeypair()
	if err != nil {
		t.Fatalf("client keypair: %v", err)
	}
	server, err := GenerateKeypair()
	if err != nil {
		t.Fatalf("server keypair: %v", err)
	}

	serverKey, err := DeriveSharedSecret(client.Public, server.Private)
	if err != nil {
		t.Fatalf("server derive: %v", err)
	}
	clientKey, err := DeriveSharedSecret(server.Public, client.Private)
	if err != nil {
		t.Fatalf("client derive: %v", err)
	}
	if !bytes.Equal(serverKey, clientKey) {
		t.Fatal("shared secret is not commutative between client and server")
	}

	plaintext := []byte("ak_roundtrip_test_key_material")
	nonce, ciphertext, tag, err := Encrypt(plaintext, serverKey)
	if err != nil {
		t.Fatalf("Encrypt: %v", err)
	}
	got, err := Decrypt(ciphertext, tag, nonce, clientKey)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if !bytes.Equal(got, plaintext) {
		t.Errorf("roundtrip mismatch\n want: %q\n got:  %q", plaintext, got)
	}
}

func TestNonceIsFreshEachEncrypt(t *testing.T) {
	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		t.Fatal(err)
	}
	plaintext := []byte("same plaintext twice")

	n1, _, _, err := Encrypt(plaintext, key)
	if err != nil {
		t.Fatalf("encrypt 1: %v", err)
	}
	n2, _, _, err := Encrypt(plaintext, key)
	if err != nil {
		t.Fatalf("encrypt 2: %v", err)
	}
	if bytes.Equal(n1, n2) {
		t.Error("consecutive encryptions produced the same nonce")
	}
	if len(n1) != 12 {
		t.Errorf("nonce should be 12 bytes, got %d", len(n1))
	}
}

// --- Tamper detection ---------------------------------------------------

func flipFirstByte(b []byte) []byte {
	out := make([]byte, len(b))
	copy(out, b)
	out[0] ^= 0xFF
	return out
}

func TestTamperedCiphertextFailsAuth(t *testing.T) {
	key := make([]byte, 32)
	rand.Read(key)
	nonce, ct, tag, err := Encrypt([]byte("hello"), key)
	if err != nil {
		t.Fatal(err)
	}
	tampered := flipFirstByte(ct)
	if _, err := Decrypt(tampered, tag, nonce, key); err == nil {
		t.Fatal("decrypt should have failed on tampered ciphertext")
	}
}

func TestTamperedTagFailsAuth(t *testing.T) {
	key := make([]byte, 32)
	rand.Read(key)
	nonce, ct, tag, err := Encrypt([]byte("hello"), key)
	if err != nil {
		t.Fatal(err)
	}
	tamperedTag := flipFirstByte(tag)
	if _, err := Decrypt(ct, tamperedTag, nonce, key); err == nil {
		t.Fatal("decrypt should have failed on tampered tag")
	}
}

func TestTamperedNonceFailsAuth(t *testing.T) {
	key := make([]byte, 32)
	rand.Read(key)
	nonce, ct, tag, err := Encrypt([]byte("hello"), key)
	if err != nil {
		t.Fatal(err)
	}
	tamperedNonce := flipFirstByte(nonce)
	if _, err := Decrypt(ct, tag, tamperedNonce, key); err == nil {
		t.Fatal("decrypt should have failed on tampered nonce")
	}
}

func TestWrongKeyFailsAuth(t *testing.T) {
	key := make([]byte, 32)
	wrongKey := make([]byte, 32)
	rand.Read(key)
	rand.Read(wrongKey)
	nonce, ct, tag, err := Encrypt([]byte("hello"), key)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Decrypt(ct, tag, nonce, wrongKey); err == nil {
		t.Fatal("decrypt should have failed with wrong key")
	}
}

// --- Validation errors --------------------------------------------------

func TestDecryptRejectsBadKeyLength(t *testing.T) {
	_, err := Decrypt([]byte("x"), make([]byte, 16), make([]byte, 12), make([]byte, 31))
	if err == nil {
		t.Fatal("decrypt should reject a 31-byte key")
	}
}

func TestDecryptRejectsBadNonceLength(t *testing.T) {
	_, err := Decrypt([]byte("x"), make([]byte, 16), make([]byte, 11), make([]byte, 32))
	if err == nil {
		t.Fatal("decrypt should reject an 11-byte nonce")
	}
}

func TestDecryptRejectsBadTagLength(t *testing.T) {
	_, err := Decrypt([]byte("x"), make([]byte, 15), make([]byte, 12), make([]byte, 32))
	if err == nil {
		t.Fatal("decrypt should reject a 15-byte tag")
	}
}
